# wueasy - A Java Distributed Rapid Development Platform.
# Copyright (C) 2017-2019 wueasy.com

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

wueasy : 
  datasource : 
    easyadmin : 
      mybatis:
        basePackage: com.wueasy.*.mapper
        mapperLocations: classpath*:mybatis/wueasy/**/*.xml
      connection: 
        url : jdbc:mysql://localhost:3306/easy_data?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username : easyadmin
        password : easyadmin
        #连接池配置
        initialSize : 10  #初始化大小
        minIdle : 10  #最小连接
        maxActive : 20  #最大连接
        maxWait : 60000  #配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis : 2000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis : 600000  #配置一个连接在池中最小生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis : 600000  #配置一个连接在池中最大生存的时间，单位是毫秒
        validationQuery : SELECT 1 from dual 
        testWhileIdle : true
        testOnBorrow : false
        testOnReturn : false
        keepAlive : true
  zipkin: #链路跟踪配置
    enabled: true #是否启用，默认false
    url: http://zipkin.wueasy.com:9411/api/v2/spans
  elk: #elk日志管理
    url: elk.wueasy.com:5000
#  localIp : 127.0.0.1 #指定本机ip地址
  zk : 
    servers : 127.0.0.1:2181
    sessionTimeout : 3000
    connectionTimeout : 5000
  bus : 
    #服务端配置
    server : 
      port : 10200 #端口
      group : wueasy-admin #分组
      minWorkerThread : 20 #最小工作pool线程数
      maxWorkerThread : 50 #最大工作pool线程数
  job : #定时任务配置
    zkConnectString : ${wueasy.zk.servers} #注册中心字符串
    namespace : wueasy-task #注册中心命名空间
    digest :  #注册中心凭证