# wueasy - A Java Distributed Rapid Development Platform.
# Copyright (C) 2017-2019 wueasy.com

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

spring:
  datasource : 
    druid : 
      url : jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username : easyadmin
      password : easyadmin
#      url : jdbc:postgresql://localhost:5432/wueasydb
#      username : wueasy
#      password : wueasy
#      url : jdbc:sqlserver://47.100.224.143:1433; DatabaseName=wueasy_data
#      username : sa
#      password : xx@123456
#      url : jdbc:mariadb://47.100.224.143:3306/easy_data
#      username : wueasy
#      password : wueasy
      #连接池配置
      initial-size : 10  #初始化大小
      min-idle : 10  #最小连接
      max-active : 20  #最大连接
      max-wait : 60000  #配置获取连接等待超时的时间
      pool-prepared-statements : true  #打开PSCache，并且指定每个连接上PSCache的大小(如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false。)
      max-pool-prepared-statement-per-connection-size : 20
#      validation-query : SELECT 1 from dual 
      test-on-borrow : false 
      test-on-return : false
      test-while-idle : true
      min-evictable-idle-time-millis : 300000  #配置一个连接在池中最小生存的时间，单位是毫秒
      time-between-eviction-runs-millis : 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒

wueasy : 
  zipkin: 
    enabled: true #是否启用，默认false
    url: http://zipkin.wueasy.com:9411/api/v2/spans
#  localIp : 127.0.0.1 #指定本机ip地址
  zk : 
    servers : 127.0.0.1:2181
    sessionTimeout : 3000
    connectionTimeout : 5000
  bus : 
    #服务端配置
    server : 
      port : 10200 #端口
      group : wueasy-admin #分组
      minWorkerThread : 20 #最小工作pool线程数
      maxWorkerThread : 50 #最大工作pool线程数
  job : #定时任务配置
    zkConnectString : ${wueasy.zk.servers} #注册中心字符串
    namespace : wueasy-task #注册中心命名空间
    digest :  #注册中心凭证